apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service
  name: nginx-service
  namespace: demo-app
spec:
  ports:
  - name: 80-80
    nodePort: 31001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-app
  type: NodePort