name: deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docker Branch
        uses: actions/checkout@v3
        with:
          ref: docker/apache